### ISSUE TITLE
Finalize syllabus

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/cythonup#3]
Work out a syllabus for all the three sections of the course.

Contributors: @clsung, @tjwei, @yungyuc

**Comment by yungyuc** [comment]
I have drafted my part and we'll wait for contribution from @clsung .

@l34marr can you track the progress and the schedule with this ticket?

**Comment by l34marr** [comment]
@yungyuc yes. I plan to set up the KKTIX page by this Wed. @clsung please add syllabus outline first before this Wed, and it's OK to include lecture notes and slides by next week.
